import home1 from "../assets/home-1.png";
import home2 from "../assets/home-2.png";
import home3 from "../assets/home-3.png";
import home4 from "../assets/home-4.png";
import home5 from "../assets/home-5.png";
import home6 from "../assets/home-6.png";
import home7 from "../assets/home-7.png";
import home8 from "../assets/home-8.png";
import home9 from "../assets/home-9.png";
import home10 from "../assets/home-10.png";
import home11 from "../assets/home-11.png";
import home12 from "../assets/home-12.png";
import home13 from "../assets/home-13.png";
import home14 from "../assets/home-14.png";
import home15 from "../assets/home-15.png";
import home16 from "../assets/home-16.png";
import home17 from "../assets/home-17.png";
import home18 from "../assets/home-18.png";
import home19 from "../assets/home-19.png";
import home20 from "../assets/home-20.png";
import home21 from "../assets/home-21.png";
import home22 from "../assets/home-22.png";

export const homeData = [
  {
    id: 1,
    image: home1,
    price: 1000000,
    size: "2000 sqft",
    bedrooms: 3,
    bathrooms: 2,
    description: "Beautiful home in the heart of the city.",
    owner: null,
    reserved: {
      name: "Henn100x",
      image:
        "https://cdn.kolscan.io/profiles/FRbUNvGxYNC1eFngpn7AD3f14aKKTJVC6zSMtvj2dyCS.png",
      x_profile: "https://x.com/henn100x",
    },
    x: 62,
    y: 12,
  },
  {
    id: 2,
    image: home2,
    price: 1200000,
    size: "2500 sqft",
    bedrooms: 4,
    bathrooms: 3,
    description: "Spacious home with a large backyard.",
    owner: null,
    x: 160,
    y: 12,
  },
  {
    id: 3,
    image: home3,
    price: 1500000,
    size: "3000 sqft",
    bedrooms: 5,
    bathrooms: 4,
    description: "Luxurious home with modern amenities.",
    owner: {
      name: "Cented",
      image: "https://thectmostwanted.com/Cented.png",
      x_profile: "https://x.com/Cented7",
    },
    x: 31,
    y: 38,
  },
  {
    id: 4,
    image: home4,
    price: 800000,
    size: "1800 sqft",
    bedrooms: 3,
    bathrooms: 2,
    description: "Cozy home in a quiet neighborhood.",
    owner: {
      name: "Kadenox",
      image: "https://thectmostwanted.com/Kadenox.png",
      x_profile: "https://x.com/kadenox",
    },
    x: 88,
    y: 92,
  },
  {
    id: 5,
    image: home5,
    home_type: "Luxury Home",
    price: 950000,
    size: "2200 sqft",
    bedrooms: 4,
    bathrooms: 3,
    description: "Charming home with a beautiful garden.",
    owner: {
      name: "dv",
      image: "https://thectmostwanted.com/dv.png",
      x_profile: "https://x.com/vibed333",
    },
    x: 67,
    y: 96,
  },
  {
    id: 6,
    image: home14,
    price: 1100000,
    size: "2600 sqft",
    bedrooms: 5,
    bathrooms: 4,
    description: "Modern home with an open floor plan.",
    owner: null,
    x: 14,
    y: 15,
  },
  {
    id: 7,
    image: home14,
    price: 1300000,
    size: "2800 sqft",
    bedrooms: 6,
    bathrooms: 5,
    description: "Elegant home with high ceilings and large windows.",
    owner: null,
    x: 4,
    y: 22,
  },
  {
    id: 8,
    image: home17,
    home_typee: "Luxury Home",
    price: 13400000,
    size: "2900 sqft",
    bedrooms: 7,
    bathrooms: 6,
    description: "Stunning home with a pool and outdoor entertainment area.",
    owner: {
      name: "Solstice",
      image:
        "https://cdn.kolscan.io/profiles/GrD2umbfEBjQKFPDQvmmYNQ5eyRL9SAdWJj9FFMyeaDN.png",
      x_profile: "https://x.com/The__Solstice",
    },
    x: 157,
    y: 100,
  },
  {
    id: 9,
    image: home1,
    price: 1600000,
    size: "3200 sqft",
    bedrooms: 8,
    bathrooms: 7,
    description: "Luxury home with a home theater and gym.",
    owner: null,
    x: 104,
    y: 36,
  },
  {
    id: 10,
    image: home10,
    price: 1700000,
    size: "3500 sqft",
    bedrooms: 9,
    bathrooms: 8,
    description: "Grand home with a library and study.",
    owner: null,
    x: 87,
    y: 7,
  },
  {
    id: 11,
    image: home11,
    price: 1800000,
    size: "3700 sqft",
    bedrooms: 10,
    bathrooms: 9,
    description: "Magnificent home with a wine cellar and bar.",
    owner: null,

    x: 1,
    y: 57,
  },
  {
    id: 12,
    image: home12,
    price: 1900000,
    size: "4000 sqft",
    bedrooms: 11,
    bathrooms: 10,
    description: "Opulent home with a spa and sauna.",
    owner: null,
    x: 20,
    y: 28,
  },
  {
    id: 13,
    image: home13,
    price: 2000000,
    size: "4500 sqft",
    bedrooms: 12,
    bathrooms: 11,
    description: "Lavish home with a rooftop terrace and outdoor kitchen.",
    owner: {
      name: "Smokez",
      image:
        "https://cdn.kolscan.io/profiles/5t9xBNuDdGTGpjaPTx6hKd7sdRJbvtKS8Mhq6qVbo8Qz.png",
      x_profile: "https://x.com/SmokezXBT",
    },
    x: 93,
    y: 78,
  },
  {
    id: 14,
    image: home21,
    price: 2100000,
    size: "5000 sqft",
    bedrooms: 13,
    bathrooms: 12,
    description: "Exquisite home with a guest house and pool house.",
    owner: null,
    x: 145,
    y: 73,
  },
  {
    id: 15,
    image: home15,
    price: 2200000,
    size: "5500 sqft",
    bedrooms: 14,
    bathrooms: 13,
    description: "Spectacular home with a tennis court and basketball court.",
    owner: null,
    x: 0,
    y: 45,
  },
  {
    id: 16,
    image: home16,
    price: 2300000,
    size: "6000 sqft",
    bedrooms: 15,
    bathrooms: 14,
    description: "Stately home with a formal dining room and grand foyer.",
    owner: null,
    x: 1,
    y: 76,
  },
  {
    id: 17,
    image: home17,
    home_typee: "Luxury Home",
    price: 6400000,
    size: "6500 sqft",
    bedrooms: 16,
    bathrooms: 15,
    description: "Impressive home with a media room and game room.",
    owner: null,
    x: 137,
    y: 99,
  },
  {
    id: 18,
    image: home18,
    home_type: "Luxury Home",
    price: 7500000,
    size: "7000 sqft",
    bedrooms: 17,
    bathrooms: 16,
    description: "Stunning home with a library and study.",
    owner: null,
    reserved: {
      name: "Fashr",
      image:
        "https://cdn.kolscan.io/profiles/719sfKUjiMThumTt2u39VMGn612BZyCcwbM5Pe8SqFYz.png",
      x_profile: "https://x.com/FASHRCrypto",
    },
    x: 58,
    y: 34,
  },
  {
    id: 19,
    image: home19,
    price: 2600000,
    size: "7500 sqft",
    bedrooms: 18,
    bathrooms: 17,
    description: "Magnificent home with a wine cellar and bar.",
    owner: null,
    x: 4,
    y: 65,
  },
  {
    id: 20,
    image: home12,
    price: 2700000,
    size: "8000 sqft",
    bedrooms: 19,
    bathrooms: 18,
    description: "Opulent home with a spa and sauna.",
    owner: null,
    x: 98,
    y: 95,
  },
  {
    id: 21,
    image: home21,
    price: 2800000,
    size: "8500 sqft",
    bedrooms: 20,
    bathrooms: 19,
    description: "Lavish home with a rooftop terrace and outdoor kitchen.",
    owner: {
      name: "Dex",
      image:
        "https://cdn.kolscan.io/profiles/mW4PZB45isHmnjGkLpJvjKBzVS5NXzTJ8UDyug4gTsM.png",
      x_profile: "https://x.com/absolquant",
    },
    x: 90,
    y: 37,
  },
  {
    id: 22,
    image: home22,
    price: 2900000,
    size: "9000 sqft",
    bedrooms: 21,
    bathrooms: 20,
    description: "Exquisite home with a guest house and pool house.",
    owner: null,
    x: 86,
    y: 70,
  },
  {
    id: 23,
    image: home1,
    price: 3000000,
    size: "9500 sqft",
    bedrooms: 22,
    bathrooms: 21,
    description: "Spectacular home with a tennis court and basketball court.",
    owner: null,
    x: 20,
    y: 55,
  },
  {
    id: 24,
    image: home2,
    price: 3100000,
    size: "10000 sqft",
    bedrooms: 23,
    bathrooms: 22,
    description: "Stately home with a formal dining room and grand foyer.",
    owner: {
      name: "Cooker",
      image:
        "https://cdn.kolscan.io/profiles/8deJ9xeUvXSJwicYptA9mHsU2rN2pDx37KWzkDkEXhU6.png",
      x_profile: "https://x.com/CookerFlips",
    },
    x: 13,
    y: 40,
  },
  {
    id: 25,
    image: home3,
    price: 3200000,
    size: "10500 sqft",
    bedrooms: 24,
    bathrooms: 23,
    description: "Impressive home with a media room and game room.",
    owner: null,
    x: 45,
    y: 45,
  },
  {
    id: 26,
    image: home4,
    price: 3300000,
    size: "11000 sqft",
    bedrooms: 25,
    bathrooms: 24,
    description: "Stunning home with a library and study.",
    owner: {
      name: "Loopierr",
      image:
        "https://cdn.kolscan.io/profiles/9yYya3F5EJoLnBNKW6z4bZvyQytMXzDcpU5D6yYr4jqL.png",
      x_profile: "Mr. Frog",
    },
    x: 146,
    y: 15,
  },
  {
    id: 27,
    image: home17,
    home_typee: "Luxury Home",
    price: 3400000,
    size: "11500 sqft",
    bedrooms: 26,
    bathrooms: 25,
    description: "Magnificent home with a wine cellar and bar.",
    owner: null,
    reserved: {
      name: "Classic",
      image:
        "https://cdn.kolscan.io/profiles/DsqRyTUh1R37asYcVf1KdX4CNnz5DKEFmnXvgT4NfTPE.png",
      x_profile: "https://x.com/simplyclassic69",
    },
    x: 169,
    y: 96,
  },
  {
    id: 28,
    image: home6,
    price: 3500000,
    size: "12000 sqft",
    bedrooms: 27,
    bathrooms: 26,
    description: "Opulent home with a spa and sauna.",
    owner: null,
    x: 39,
    y: 31,
  },
  {
    id: 29,
    image: home20,
    price: 3600000,
    size: "12500 sqft",
    bedrooms: 28,
    bathrooms: 27,
    description: "Lavish home with a rooftop terrace and outdoor kitchen.",
    owner: null,
    x: 20,
    y: 7,
  },
  {
    id: 30,
    image: home8,
    price: 3700000,
    size: "13000 sqft",
    bedrooms: 29,
    bathrooms: 28,
    description: "Exquisite home with a guest house and pool house.",
    owner: null,
    x: 35,
    y: 3,
  },
  {
    id: 31,
    image: home9,
    price: 3800000,
    size: "13500 sqft",
    bedrooms: 30,
    bathrooms: 29,
    description: "Spectacular home with a tennis court and basketball court.",
    owner: null,
    x: 54,
    y: 7,
  },
  {
    id: 32,
    image: home10,
    price: 3900000,
    size: "14000 sqft",
    bedrooms: 31,
    bathrooms: 30,
    description: "Stately home with a formal dining room and grand foyer.",
    owner: null,
    x: 65,
    y: 3,
  },
  {
    id: 33,
    image: home11,
    price: 4000000,
    size: "14500 sqft",
    bedrooms: 32,
    bathrooms: 31,
    description: "Impressive home with a media room and game room.",
    owner: null,
    x: 96,
    y: 0,
  },
  {
    id: 34,
    image: home12,
    price: 4100000,
    size: "15000 sqft",
    bedrooms: 33,
    bathrooms: 32,
    description: "Stunning home with a library and study.",
    owner: null,
    x: 108,
    y: 55,
  },
  {
    id: 35,
    image: home13,
    price: 4200000,
    size: "15500 sqft",
    bedrooms: 34,
    bathrooms: 33,
    description: "Magnificent home with a wine cellar and bar.",
    owner: null,
    x: 136,
    y: 56,
  },
  {
    id: 36,
    image: home1,
    price: 4300000,
    size: "16000 sqft",
    bedrooms: 35,
    bathrooms: 34,
    description: "Opulent home with a spa and sauna.",
    owner: null,
    x: 14,
    y: 90,
  },
  {
    id: 37,
    image: home15,
    price: 4400000,
    size: "16500 sqft",
    bedrooms: 36,
    bathrooms: 35,
    description: "Lavish home with a rooftop terrace and outdoor kitchen.",
    owner: null,
    x: 76,
    y: 12,
  },
  {
    id: 38,
    image: home16,
    price: 4500000,
    size: "17000 sqft",
    bedrooms: 37,
    bathrooms: 36,
    description: "Exquisite home with a guest house and pool house.",
    owner: null,
    x: 183,
    y: 17,
  },
  {
    id: 39,
    image: home17,
    home_typee: "Luxury Home",
    price: 4600000,
    size: "17500 sqft",
    bedrooms: 38,
    bathrooms: 37,
    description: "Spectacular home with a tennis court and basketball court.",
    owner: null,
    x: 144,
    y: 104,
  },
  {
    id: 40,
    image: home18,
    home_type: "Luxury Home",
    price: 4700000,
    size: "18000 sqft",
    bedrooms: 39,
    bathrooms: 38,
    description: "Stately home with a formal dining room and grand foyer.",
    owner: null,
    x: 80,
    y: 27,
  },
  {
    id: 41,
    image: home19,
    price: 4800000,
    size: "18500 sqft",
    bedrooms: 40,
    bathrooms: 39,
    description: "Impressive home with a media room and game room.",
    owner: null,
    x: 186,
    y: 4,
  },
  {
    id: 42,
    image: home21,
    price: 4900000,
    size: "19000 sqft",
    bedrooms: 41,
    bathrooms: 40,
    description: "Stunning home with a library and study.",
    owner: {
      name: "Kreo",
      image: "https://thectmostwanted.com/Kreo.png",
      x_profile: "https://x.com/kreo444",
    },
    x: 131,
    y: 44,
  },
  {
    id: 43,
    image: home21,
    price: 5000000,
    size: "19500 sqft",
    bedrooms: 42,
    bathrooms: 41,
    description: "Magnificent home with a wine cellar and bar.",
    owner: null,
    x: 73,
    y: 61,
  },
  {
    id: 44,
    image: home21,
    price: 5100000,
    size: "20000 sqft",
    bedrooms: 43,
    bathrooms: 42,
    description: "Opulent home with a spa and sauna.",
    owner: null,
    x: 164,
    y: 80,
  },
  {
    id: 45,
    image: home1,
    price: 5200000,
    size: "20500 sqft",
    bedrooms: 44,
    bathrooms: 43,
    description: "Lavish home with a rooftop terrace and outdoor kitchen.",
    owner: null,
    x: 109,
    y: 11,
  },
  {
    id: 46,
    image: home2,
    price: 5300000,
    size: "21000 sqft",
    bedrooms: 45,
    bathrooms: 44,
    description: "Exquisite home with a guest house and pool house.",
    owner: null,
    x: 58,
    y: 75,
  },
  {
    id: 47,
    image: home3,
    price: 5400000,
    size: "21500 sqft",
    bedrooms: 46,
    bathrooms: 45,
    description: "Spectacular home with a tennis court and basketball court.",
    owner: null,
    x: 122,
    y: 10,
  },
  {
    id: 48,
    image: home4,
    price: 5500000,
    size: "22000 sqft",
    bedrooms: 47,
    bathrooms: 46,
    description: "Stately home with a formal dining room and grand foyer.",
    owner: null,
    x: 19,
    y: 68,
  },
  {
    id: 49,
    image: home5,
    home_type: "Luxury Home",
    price: 5600000,
    size: "22500 sqft",
    bedrooms: 48,
    bathrooms: 47,
    description: "Impressive home with a media room and game room.",
    owner: null,
    x: 75,
    y: 106,
  },
  {
    id: 50,
    image: home6,
    price: 5700000,
    size: "23000 sqft",
    bedrooms: 49,
    bathrooms: 48,
    description: "Stunning home with a library and study.",
    owner: null,
    x: 73,
    y: 44,
  },
  {
    id: 51,
    image: home7,
    price: 5800000,
    size: "23500 sqft",
    bedrooms: 50,
    bathrooms: 49,
    description: "Magnificent home with a wine cellar and bar.",
    owner: null,
    x: 91,
    y: 54,
  },
  {
    id: 52,
    image: home8,
    price: 5900000,
    size: "24000 sqft",
    bedrooms: 51,
    bathrooms: 50,
    description: "Opulent home with a spa and sauna.",
    owner: null,
    x: 75,
    y: 2,
  },
  {
    id: 53,
    image: home9,
    price: 6000000,
    size: "24500 sqft",
    bedrooms: 52,
    bathrooms: 51,
    description: "Lavish home with a rooftop terrace and outdoor kitchen.",
    owner: null,
    x: 142,
    y: 0,
  },
  {
    id: 54,
    image: home10,
    price: 6100000,
    size: "25000 sqft",
    bedrooms: 53,
    bathrooms: 52,
    description: "Exquisite home with a guest house and pool house.",
    owner: null,
    x: 131,
    y: 18,
  },
  {
    id: 55,
    image: home18,
    home_type: "Luxury Home",
    price: 11000000,
    size: "25500 sqft",
    bedrooms: 54,
    bathrooms: 53,
    description: "Spectacular home with a tennis court and basketball court.",
    owner: {
      name: "West",
      image: "https://thectmostwanted.com/West.png",
      x_profile: "https://x.com/ratwizardx",
    },
    x: 68,
    y: 25,
  },
  {
    id: 56,
    image: home12,
    price: 6300000,
    size: "26000 sqft",
    bedrooms: 55,
    bathrooms: 54,
    description: "Stately home with a formal dining room and grand foyer.",
    owner: null,
    x: 34,
    y: 17,
  },
  {
    id: 57,
    image: home13,
    price: 6400000,
    size: "26500 sqft",
    bedrooms: 56,
    bathrooms: 55,
    description: "Impressive home with a media room and game room.",
    owner: null,
    x: 90,
    y: 15,
  },
  {
    id: 58,
    image: home4,
    price: 6500000,
    size: "27000 sqft",
    bedrooms: 57,
    bathrooms: 56,
    description: "Stunning home with a library and study.",
    owner: null,
    x: 39,
    y: 79,
  },
  {
    id: 59,
    image: home15,
    price: 1000000,
    size: "27500 sqft",
    bedrooms: 58,
    bathrooms: 57,
    description: "Magnificent home with a wine cellar and bar.",
    owner: null,
    x: 50,
    y: 20,
  },
  {
    id: 60,
    image: home16,
    price: 700000,
    size: "28000 sqft",
    bedrooms: 59,
    bathrooms: 58,
    description: "Opulent home with a spa and sauna.",
    owner: null,
    x: 166,
    y: 0,
  },
  {
    id: 61,
    image: home3,
    price: 5400000,
    size: "21500 sqft",
    bedrooms: 46,
    bathrooms: 45,
    description: "Spectacular home with a tennis court and basketball court.",
    owner: null,
    x: 79,
    y: 82,
  },
  {
    id: 62,
    image: home4,
    price: 5500000,
    size: "22000 sqft",
    bedrooms: 47,
    bathrooms: 46,
    description: "Stately home with a formal dining room and grand foyer.",
    owner: null,
    x: 110,
    y: 0,
  },
  {
    id: 63,
    image: home5,
    home_type: "Luxury Home",
    price: 15600000,
    size: "22500 sqft",
    bedrooms: 48,
    bathrooms: 47,
    description: "Impressive home with a media room and game room.",
    owner: null,
    x: 55,
    y: 105,
  },
  {
    id: 64,
    image: home6,
    price: 5700000,
    size: "23000 sqft",
    bedrooms: 49,
    bathrooms: 48,
    description: "Stunning home with a library and study.",
    owner: null,
    x: 130,
    y: 0,
  },
  {
    id: 65,
    image: home3,
    price: 5800000,
    size: "23500 sqft",
    bedrooms: 50,
    bathrooms: 49,
    description: "Magnificent home with a wine cellar and bar.",
    owner: null,
    reserved: {
      name: "Cooker",
      image:
        "https://cdn.kolscan.io/profiles/8deJ9xeUvXSJwicYptA9mHsU2rN2pDx37KWzkDkEXhU6.png",
      x_profile: "https://x.com/CookerFlips",
    },
    x: 25,
    y: 93,
  },
  {
    id: 66,
    image: home21,
    price: 5900000,
    size: "24000 sqft",
    bedrooms: 51,
    bathrooms: 50,
    description: "Opulent home with a spa and sauna.",
    owner: null,
    x: 175,
    y: 65,
  },
  {
    id: 67,
    image: home20,
    price: 6000000,
    size: "24500 sqft",
    bedrooms: 52,
    bathrooms: 51,
    description: "Lavish home with a rooftop terrace and outdoor kitchen.",
    owner: null,
    x: 1,
    y: 16,
  },
  {
    id: 68,
    image: home10,
    price: 6100000,
    size: "25000 sqft",
    bedrooms: 53,
    bathrooms: 52,
    description: "Exquisite home with a guest house and pool house.",
    owner: null,
    x: 48,
    y: 3,
  },
  {
    id: 69,
    image: home21,
    price: 12000000,
    size: "25500 sqft",
    bedrooms: 54,
    bathrooms: 53,
    description: "Spectacular home with a tennis court and basketball court.",
    owner: null,
    x: 187,
    y: 50,
  },
  {
    id: 70,
    image: home12,
    price: 6300000,
    size: "26000 sqft",
    bedrooms: 55,
    bathrooms: 54,
    description: "Stately home with a formal dining room and grand foyer.",
    owner: null,
    x: 114,
    y: 78,
  },
  {
    id: 71,
    image: home13,
    price: 6400000,
    size: "26500 sqft",
    bedrooms: 56,
    bathrooms: 55,
    description: "Impressive home with a media room and game room.",
    owner: null,
    x: 145,
    y: 44,
  },
  {
    id: 72,
    image: home5,
    home_type: "Luxury Home",
    price: 6500000,
    size: "27000 sqft",
    bedrooms: 57,
    bathrooms: 56,
    description: "Stunning home with a library and study.",
    owner: {
      name: "Euris",
      image: "https://thectmostwanted.com/Euris.png",
      x_profile: "https://x.com/Euris_JT",
    },
    x: 38,
    y: 100,
  },
  {
    id: 73,
    image: home15,
    price: 1000000,
    size: "27500 sqft",
    bedrooms: 58,
    bathrooms: 57,
    description: "Magnificent home with a wine cellar and bar.",
    owner: null,
    x: 128,
    y: 28,
  },
  {
    id: 74,
    image: home16,
    price: 700000,
    size: "28000 sqft",
    bedrooms: 59,
    bathrooms: 58,
    description: "Opulent home with a spa and sauna.",
    owner: null,
    x: 188,
    y: 30,
  },
  {
    id: 75,
    image: home3,
    price: 5400000,
    size: "21500 sqft",
    bedrooms: 46,
    bathrooms: 45,
    description: "Spectacular home with a tennis court and basketball court.",
    owner: null,

    x: 35,
    y: 50,
  },
  {
    id: 76,
    image: home4,
    price: 5500000,
    size: "22000 sqft",
    bedrooms: 47,
    bathrooms: 46,
    description: "Stately home with a formal dining room and grand foyer.",
    owner: {
      name: "Heyitsyolo",
      image:
        "https://cdn.kolscan.io/profiles/Av3xWHJ5EsoLZag6pr7LKbrGgLRTaykXomDD5kBhL9YQ.png",
      x_profile: "https://x.com/Heyitsyolotv",
    },
    x: 111,
    y: 22,
  },
  {
    id: 77,
    image: home5,
    home_type: "Luxury Home",
    price: 5600000,
    size: "22500 sqft",
    bedrooms: 48,
    bathrooms: 47,
    description: "Impressive home with a media room and game room.",
    owner: null,
    reserved: {
      name: "Absol",
      image:
        "https://cdn.kolscan.io/profiles/BXNiM7pqt9Ld3b2Hc8iT3mA5bSwoe9CRrtkSUs15SLWN.png",
      x_profile: "#",
    },
    x: 50,
    y: 94,
  },
  {
    id: 78,
    image: home6,
    price: 5700000,
    size: "23000 sqft",
    bedrooms: 49,
    bathrooms: 48,
    description: "Stunning home with a library and study.",
    owner: null,
    x: 40,
    y: 10,
  },
  {
    id: 79,
    image: home13,
    price: 5800000,
    size: "23500 sqft",
    bedrooms: 50,
    bathrooms: 49,
    description: "Magnificent home with a wine cellar and bar.",
    owner: null,
    x: 158,
    y: 56,
  },
  {
    id: 80,
    image: home8,
    price: 5900000,
    size: "24000 sqft",
    bedrooms: 51,
    bathrooms: 50,
    description: "Opulent home with a spa and sauna.",
    owner: null,
    x: 61,
    y: 59,
  },
  {
    id: 81,
    image: home9,
    price: 6000000,
    size: "24500 sqft",
    bedrooms: 52,
    bathrooms: 51,
    description: "Lavish home with a rooftop terrace and outdoor kitchen.",
    owner: null,
    x: 152,
    y: 0,
  },
  {
    id: 82,
    image: home17,
    home_typee: "Luxury Home",
    price: 6100000,
    size: "25000 sqft",
    bedrooms: 53,
    bathrooms: 52,
    description: "Exquisite home with a guest house and pool house.",
    owner: null,
    x: 179,
    y: 85,
  },
  {
    id: 83,
    image: home13,
    price: 10500000,
    size: "25500 sqft",
    bedrooms: 54,
    bathrooms: 53,
    description: "Spectacular home with a tennis court and basketball court.",
    owner: null,
    reserved: {
      name: "Mr. Frog",
      image:
        "https://cdn.kolscan.io/profiles/4DdrfiDHpmx55i4SPssxVzS9ZaKLb8qr45NKY9Er9nNh.png",
      x_profile: "#",
    },
    x: 120,
    y: 55,
  },
  {
    id: 84,
    image: home12,
    price: 6300000,
    size: "26000 sqft",
    bedrooms: 55,
    bathrooms: 54,
    description: "Stately home with a formal dining room and grand foyer.",
    owner: null,
    x: 40,
    y: 63,
  },
  {
    id: 85,
    image: home13,
    price: 6400000,
    size: "26500 sqft",
    bedrooms: 56,
    bathrooms: 55,
    description: "Impressive home with a media room and game room.",
    owner: {
      name: "Danny",
      image: "https://thectmostwanted.com/Danny.png",
      x_profile: "https://x.com/0xSevere",
    },
    x: 170,
    y: 33,
  },
  {
    id: 86,
    image: home1,
    price: 6500000,
    size: "27000 sqft",
    bedrooms: 57,
    bathrooms: 56,
    description: "Stunning home with a library and study.",
    owner: null,
    x: 155,
    y: 30,
  },
  {
    id: 87,
    image: home15,
    price: 1000000,
    size: "27500 sqft",
    bedrooms: 58,
    bathrooms: 57,
    description: "Magnificent home with a wine cellar and bar.",
    owner: null,
    x: 117,
    y: 33,
  },
  {
    id: 88,
    image: home16,
    price: 700000,
    size: "28000 sqft",
    bedrooms: 59,
    bathrooms: 58,
    description: "Opulent home with a spa and sauna.",
    owner: null,
    x: 175,
    y: 8,
  },
  {
    id: 89,
    image: home17,
    home_typee: "Luxury Home",
    price: 6400000,
    size: "6500 sqft",
    bedrooms: 16,
    bathrooms: 15,
    description: "Impressive home with a media room and game room.",
    owner: {
      name: "Tim",
      image:
        "https://cdn.kolscan.io/profiles/AJ6MGExeK7FXmeKkKPmALjcdXVStXYokYNv9uVfDRtvo.png",
      x_profile: "https://x.com/timmpix1",
    },
    x: 125,
    y: 95,
  },
  {
    id: 90,
    image: home18,
    home_type: "Luxury Home",
    price: 2500000,
    size: "7000 sqft",
    bedrooms: 17,
    bathrooms: 16,
    description: "Stunning home with a library and study.",
    owner: null,
    x: 135,
    y: 80,
  },
  {
    id: 90,
    image: home17,
    home_typee: "Luxury Home",
    price: 2500000,
    size: "7000 sqft",
    bedrooms: 17,
    bathrooms: 16,
    description: "Stunning home with a library and study.",
    owner: null,
    reserved: {
      name: "Smokez",
      image:
        "https://cdn.kolscan.io/profiles/5t9xBNuDdGTGpjaPTx6hKd7sdRJbvtKS8Mhq6qVbo8Qz.png",
      x_profile: "https://x.com/SmokezXBT",
    },
    x: 188,
    y: 73,
  },
];
